baseURL = 'https://elwhyjay.github.io'
languageCode = 'ko-kr'
title = "Yongjun's blog"
theme = 'nostyleplease'
googleAnalytics = "G-YXXYQPDYLX"
[taxonomies]
    categories = 'categories'
    tag = 'tags'
    remind = 'reminds'
[Params]
    favicon = "img/favicon.ico"
    disable_comments = false
