[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "Github"
  url = "https://github.com/elwhyjay"
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/yongjun-lee-47b0201bb/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107